#!/bin/ash
set -e

echo APP_HOME: $APP_HOME
echo BASE_URL: $BASE_URL
echo BROWSER_BASE_URL: $BROWSER_BASE_URL
echo FIREBASE_AUTH_KEY: $FIREBASE_AUTH_KEY
echo FIREBASE_ADMIN_KEY: $FIREBASE_ADMIN_KEY

cd $APP_HOME
npm run start
