#!/bin/ash
set -e

echo APP_HOME: $APP_HOME
echo BASE_URL: $BASE_URL
echo BROWSER_BASE_URL: $BROWSER_BASE_URL
echo API_KEY: $API_KEY
echo AUTH_DOMAIN: $AUTH_DOMAIN
echo DATABASE_URL: $DATABASE_URL
echo PROJECT_ID: $PROJECT_ID
echo STORAGE_BUCKET: $STORAGE_BUCKET
echo MESSAGE_SENDER_ID: $MESSAGE_SENDER_ID
echo APP_ID: $APP_ID
echo MEASUREMENT_ID: $MEASUREMENT_ID
echo FIREBASE_TOKEN: $FIREBASE_TOKEN
echo FIREBASE_ADMIN_PROJECT_ID: $FIREBASE_ADMIN_PROJECT_ID
echo FIREBASE_ADMIN_CLIENT_EMAIL: $FIREBASE_ADMIN_CLIENT_EMAIL
echo FIREBASE_ADMIN_PRIVATE_KEY: $FIREBASE_ADMIN_PRIVATE_KEY

cd $APP_HOME
npm run start
