#!/bin/ash
set -e

echo APP_HOME: $APP_HOME
echo BASE_URL: $BASE_URL
echo BROWSER_BASE_URL: $BROWSER_BASE_URL
echo FIREBASE_ADMIN_PROJECT_ID: $FIREBASE_ADMIN_PROJECT_ID
echo FIREBASE_ADMIN_CLIENT_EMAIL: $FIREBASE_ADMIN_CLIENT_EMAIL
echo FIREBASE_ADMIN_PRIVATE_KEY: $FIREBASE_ADMIN_PRIVATE_KEY

cd $APP_HOME
npm run start
